[package]
name = "jellyfish-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
image = "0.25.1"
nalgebra = "0.32.5"
neobridge-rust = "0.1.0"
xcap = "0.0.8"
