[package]
name = "jellyfish-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
image = "0.25.1"
nalgebra = "0.32.5"
neobridge-rust = "0.1.4"
xcap = "0.0.8"
itertools = "0.13.0"
arrayvec = "0.7.4"
replace_with = "0.1.7"

[profile.release]
lto = true
opt-level = 3

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "color_benchmark"
harness = false
